version: '3.8'

services:
  springbootapp:
    container_name: spring-boot-app
    build:
      context: .  # Path to the Dockerfile for Spring Boot app
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://100.29.3.123:3306/practiceProject?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: practice_user
      SPRING_DATASOURCE_PASSWORD: practice@123
    networks:
      - practiceproject  # Define the network as a list item

volumes:
  mysql_data:
